name: Deploy on Netlify

on:
  workflow_call:
    inputs:
      service:
        description: "The service/sub-repository to deploy"
        type: string
        required: true
      
jobs:  
  deploy-to-netlify:
    name: Deploy ${{ inputs.service }} on Netlify
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check for changes in ${{ inputs.service }}
        run: |
          changed=$(scripts/monorepo.sh ${{ inputs.service }} ${{ github.ref_name }})
          echo "::set-output name=changed::$changed"
        shell: bash
        id: check_changes
      - name: Check if forked PR
        id: is_forked
        run: |
          echo "::set-output name=is_forked::${{github.repository_owner != 'Unlock Protocol' && github.event.pull_request.merged == true}}"
      - name: Set target environment
        id: set_target
        run: |
          echo "::set-output name=target::${{ contains(github.base_ref, 'production') && 'prod' || 'staging' }}"
      - name: Parse secrets prefix
        id: set_prefix
        run: |
          SERVICE_NAME="${{ inputs.service }}"
          UPCASE_SERVICE="${SERVICE_NAME^^}"
          PREFIX="${UPCASE_SERVICE//-/_}_NETLIFY_${{ steps.set_target.outputs.target }}"
          echo "::set-output name=site_id::${PREFIX^^}_SITE_ID"
          echo "::set-output name=auth_token::${PREFIX^^}_AUTH_TOKEN"
          echo "::set-output name=test_secret::HELLO"
      - name: Export secrets to env
        run: |
          echo "${{ steps.set_prefix.outputs.site_id }}=$SITE_ID" >> $GITHUB_ENV
        env:
          SITE_ID: ${{ secrets[ steps.set_prefix.outputs.site_id ] }}
          TEST: ${{ secrets[ steps.set_prefix.outputs.test_secret ] }}
      - name: Deploy to Netlify
        if: ${{ steps.check_changes.outputs.changed == 'changed' }}
        run: |
          # show args
          echo "${{ steps.set_target.outputs.target }} ${{ inputs.service }} netlify $GITHUB_SHA $GITHUB_REF_NAME ${{ steps.is_forked.outputs.is_forked }}"
          # run command
          scripts/deploy.sh ${{ steps.set_target.outputs.target }} ${{ inputs.service }} netlify "$GITHUB_SHA" "$GITHUB_REF_NAME" ${{ steps.is_forked.outputs.is_forked }}