name: Deploy on Netlify

on:
  workflow_call:
    inputs:
      service:
        description: "The service/sub-repository to deploy"
        type: string
        required: true
      
jobs:
  deploy-to-netlify:
    name: Deploy ${{ inputs.service }} on Netlify
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check for changes in ${{ inputs.service }}
        run: |
          changed=$(scripts/monorepo.sh ${{ inputs.service }} ${{ github.ref_name }})
          echo "::set-output name=changed::$changed"
        shell: bash
        id: check_changes
      - name: Check if forked PR
        id: is_forked
        run: |
          echo "::set-output name=is_forked::${{github.repository_owner != 'Unlock Protocol' && github.event.pull_request.merged == true}}"
      - name: Set target environment
        id: set_target
        run: |
          echo "::set-output name=target::${{ contains(github.base_ref, 'production') && 'prod' || 'staging' }}"
      - name: Parse secrets prefix
        id: set_prefix
        run: |
          PREFIX="${{ inputs.service }}_NETLIFY_${{ steps.set_target.outputs.target }}"
          SITE_ID="${$PREFIX^^}_SITE_ID"
          AUTH_TOKEN="${$PREFIX^^}_AUTH_TOKEN"
          echo "::set-output name=site_id::$SITE_ID"
          echo "::set-output name=auth_token::$AUTH_TOKEN"
      - name: Show Netlify script params
        run: |
          PREFIX="${{ inputs.service }}_NETLIFY_${{ steps.set_target.outputs.target }}"
          UPCASE_PREFIX="${$PREFIX^^}"
          export ${{ steps.set_prefix.outputs.site_id }}="${{ secrets[steps.set_prefix.outputs.site_id] }}"
          echo ${{ steps.set_prefix.outputs.site_id }}
          echo "${{ steps.set_target.outputs.target }} ${{ inputs.service }} netlify $GITHUB_SHA $GITHUB_REF_NAME ${{ steps.is_forked.outputs.is_forked }}"
      - name: Deploy to Netlify
        if: ${{ steps.check_changes.outputs.changed == 'changed' }}
        run: |
          scripts/deploy.sh ${{ steps.set_target.outputs.target }} ${{ inputs.service }} netlify "$GITHUB_SHA" "$GITHUB_REF_NAME" ${{ steps.is_forked.outputs.is_forked }}